# Numpy array

In [27]:
import numpy as np
a = np.array([1, 2, 1, 2])
print(a)

[1 2 1 2]


In [3]:
import numpy as np
b = np.array([(7,9,9,2), (16, 11, 9, 9)])
print(b)

[[ 7  9  9  2]
 [16 11  9  9]]


In [5]:
c = np.arange(10) # generate set of 10 int from 0
d = np.linspace(1, 5, 6) # set of values after splitting the 1 - 5 numbers in 6 equal parts
print(c)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[1.  1.8 2.6 3.4 4.2 5. ]


# Properties of numpy array

In [9]:
print(a.ndim) #dimension of array
print(a.itemsize) #Byte size of each element
print(a.dtype) #datatype of array
print(a.size*a.itemsize) #memory occupied of whole array
print(a.size) #number of elements in array
print(a.shape) #shape of array (rows and columns)
print(b.shape) #shape of array (rows and columns)

1
4
int32
16
4
(4,)
(2, 4)


In [19]:
print(b)
b = b.reshape(4, 2)
print(b)
b = b.reshape(2, 4)
print(b)

[[ 7  9]
 [ 9  2]
 [16 11]
 [ 9  9]]
[[ 7  9]
 [ 9  2]
 [16 11]
 [ 9  9]]
[[ 7  9  9  2]
 [16 11  9  9]]


In [21]:
print(b[0, 2]) #slicing the exact 0th row 2nd coln element
print(b[0:, 2]) #slicing all the elements from 0th row but only of 2nd column

9
[9 9]


In [23]:
print(a)
print(a.min())
print(a.max())
print(a.sum())

[1 0 1 0]
0
1
2


In [29]:
print(a)
print(b)

print(b.sum(axis=0)) 
print(b.sum(axis=1)) 
print(np.sqrt(a)) #square root of each element of array
print(np.std(a)) # standard deviation of array
print(np.exp(a)) # exponential of array
print(np.log(a)) #natural log - ln
print(np.log10(a)) #log base 10

[1 2 1 2]
[[ 7  9  9  2]
 [16 11  9  9]]
[23 20 18 11]
[27 45]
[1.         1.41421356 1.         1.41421356]
0.5
[2.71828183 7.3890561  2.71828183 7.3890561 ]
[0.         0.69314718 0.         0.69314718]
[0.      0.30103 0.      0.30103]


In [31]:
f = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
print(np.vstack((b, f))) # vertical stack
print(np.hstack((b, f))) # horizontal stack
print(b.ravel()) # convert to single dimension

[[ 7  9  9  2]
 [16 11  9  9]
 [ 1  2  3  4]
 [ 5  6  7  8]]
[[ 7  9  9  2  1  2  3  4]
 [16 11  9  9  5  6  7  8]]
[ 7  9  9  2 16 11  9  9]


# Three dimensional array

In [34]:
threeDArray = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[-1, -2, -3], [-4, -5, -6]]
])
print(threeDArray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]


In [36]:
print(a.dtype)
print(b.dtype)
print(threeDArray.dtype)

int32
int32
int32


In [38]:
print(a.shape)
print(b.shape)
print(threeDArray.shape)

(4,)
(2, 4)
(2, 2, 3)


In [40]:
print(a.size)
print(b.size)
print(threeDArray.size)

4
8
12


In [48]:
print(threeDArray.flatten()) #converts in single dimension
print(threeDArray.ravel())

[ 1  2  3  4  5  6 -1 -2 -3 -4 -5 -6]
[ 1  2  3  4  5  6 -1 -2 -3 -4 -5 -6]


In [46]:
print(b.flatten())

[ 7  9  9  2 16 11  9  9]


In [56]:
zeros = np.zeros(5) #array with all 0s of given size
print(zeros)

[0. 0. 0. 0. 0.]


In [58]:
ones = np.ones(8) #array with all 1s of given size
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [60]:
ones = ones.astype(int) #type casting
print(ones)

[1 1 1 1 1 1 1 1]


In [62]:
ranges = np.arange(5.6, 9.8) #arange takes decimal values unlike range
print(ranges)

[5.6 6.6 7.6 8.6 9.6]


In [64]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is exc

# Scalar Operation

In [66]:
matrix = np.array([[76, 34, 89], [23, 34, 45]])
print(matrix)

[[76 34 89]
 [23 34 45]]


In [68]:
print(matrix + 2)

[[78 36 91]
 [25 36 47]]


In [71]:
print(matrix * 2)

[[152  68 178]
 [ 46  68  90]]


In [73]:
print(matrix // 2)

[[38 17 44]
 [11 17 22]]


In [75]:
print(matrix ** 2)

[[5776 1156 7921]
 [ 529 1156 2025]]


In [77]:
print(matrix.T) #transpose matrix

[[76 23]
 [34 34]
 [89 45]]


In [79]:
print(matrix[1, ])

[23 34 45]


In [83]:
## creating an array with the specific value
full = np.full(10, 5)
print(full)
print(np.full((2, 2), 10))
print(np.full((2, 5, 4), 5))

[5 5 5 5 5 5 5 5 5 5]
[[10 10]
 [10 10]]
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


In [85]:
mat1 = np.array([[1, 2, 3], [4, 5, 6]])
mat2 = np.array([[1, 2, 3], [4, 5, 6]])

In [89]:
print(mat1 + mat2) #shape must be same

[[ 2  4  6]
 [ 8 10 12]]


In [91]:
print(mat1 - mat2)

[[0 0 0]
 [0 0 0]]


In [93]:
print(mat1 * mat2)

[[ 1  4  9]
 [16 25 36]]


In [95]:
print(mat1 / mat2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [101]:
mat1 = np.array([[1, 2], [2, 3], [3, 4]])
mat2 = np.array([[1, 2], [3, 4]])

In [103]:
print(np.matmul(mat1, mat2)) #but (n, k)* (k,m) col and row of 1st and 2nd matrix must match

[[ 7 10]
 [11 16]
 [15 22]]


In [99]:
marks = np.array([
    [87, 90, 89], [100, 87, 90],
    [94, 77, 90], [100, 86, 98]
])

In [107]:
print(marks.min())
print(marks.max())
print(marks.sum())
print(marks.mean())
print(marks.std())

77
100
1088
90.66666666666667
6.315765107165473


## Row and column wise operations

In [112]:
# axis 1 means row wise
print(marks.min(axis = 1))
print(marks.max(axis = 1))
print(marks.sum(axis = 1))
print(marks.mean(axis = 1))
print(marks.std(axis = 1))

[87 87 77 86]
[ 90 100  94 100]
[266 277 261 284]
[88.66666667 92.33333333 87.         94.66666667]
[1.24721913 5.55777733 7.25718035 6.18241233]


In [115]:
# axis 0 means column wise
print(marks.min(axis = 0))
print(marks.max(axis = 0))
print(marks.sum(axis = 0))
print(marks.mean(axis = 0))
print(marks.std(axis = 0))

[87 77 89]
[100  90  98]
[381 340 367]
[95.25 85.   91.75]
[5.35607132 4.84767986 3.63145976]


## append operation

In [120]:
x = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
y = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

In [124]:
print(np.hstack((x, y)))

[[1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]]


In [126]:
print(np.vstack((x, y)))

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [132]:
print(np.append(x, (2, 3))) # creates a new array, won't update existing one
print(x)

[1 2 3 4 1 2 3 4 2 3]
[[1 2 3 4]
 [1 2 3 4]]


In [134]:
new_array = np.array([1, 2, 3])

In [138]:
x = np.append([[1, 2, 3], [4, 5, 6]], [[1, 2, 3], new_array], axis=0)
print(x)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [1 2 3]]


In [140]:
x = np.append([[1, 2, 3], [4, 5, 6]], [[1, 2, 3], new_array], axis=1)
print(x)

[[1 2 3 1 2 3]
 [4 5 6 1 2 3]]


In [142]:
np.transpose(x)

array([[1, 4],
       [2, 5],
       [3, 6],
       [1, 1],
       [2, 2],
       [3, 3]])

In [144]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6],
       [1, 1],
       [2, 2],
       [3, 3]])

## Boolean Indexing 

In [147]:
arr = np.arange(7)
print(arr)

[0 1 2 3 4 5 6]


In [149]:
arr>7

array([False, False, False, False, False, False, False])

In [153]:
arr>4

array([False, False, False, False, False,  True,  True])

In [151]:
arr[arr>4]

array([5, 6])

In [159]:
np.arange(12).reshape((2, 3, 2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [165]:
np.random.randint(10, 20, (5, 5)) # start, stop, shape for randint

array([[18, 17, 16, 12, 16],
       [12, 18, 18, 19, 11],
       [14, 12, 15, 17, 10],
       [17, 14, 17, 11, 12],
       [13, 19, 14, 14, 14]])

In [177]:
letters = list(set("AEIOU"))

In [179]:
np.random.choice(letters, 5)

array(['A', 'E', 'U', 'E', 'O'], dtype='<U1')

In [181]:
np.random.choice(letters, 5, replace=False)

array(['O', 'U', 'A', 'E', 'I'], dtype='<U1')

In [185]:
np.random.choice(letters, 15, p=[0.4, 0.3, 0.1, 0.1, 0.1]) #probabilities

array(['O', 'O', 'E', 'A', 'O', 'E', 'O', 'U', 'E', 'E', 'E', 'O', 'E',
       'O', 'A'], dtype='<U1')

In [ ]:
array = np.random.randint(10, 20, (5, 5))
np.save(